{{- $codespaces:= env "CODESPACES" | not | not -}}
sourceDir = "{{ .chezmoi.sourceDir }}"

[data]
  name = "Tim Kleinschmidt"
  codespaces = {{ $codespaces }}
{{- if $codespaces }}{{/* Codespaces dotfiles setup is non-interactive, so set an email address */}}
  email = "tim.kleinschmidt@gmail.com"
{{- else }}{{/* Interactive setup, so prompt for an email address */}}
  email = "{{ promptString "email" }}"
{{- end }}
