tap "homebrew/cask"
tap "homebrew/cask-versions"

cask "gpg-suite"
cask "rabbitmq"
cask "virtualbox"
cask "virtualbox-extension-pack"
cask "vmware-fusion"

brew "borkdude/brew/clj-kondo"
brew "clojure-lsp"
brew "coreutils"
brew "editorconfig"
brew "languagetool"
brew "node@10"
brew "pyenv"
brew "pyenv-virtualenv"
brew "rabbitmq"
brew "terminal-notifier"

# Quicklook
cask "qlcolorcode"
cask "qlmarkdown"
cask "qlstephen"
cask "quicklook-csv"
cask "quicklook-json"
cask "qlimagesize"
cask "suspicious-package"
cask "apparency"
cask "quicklookase"
cask "qlvideo"
