#! /bin/sh

bspc config border_width            2
bspc config window_gap              10

bspc config split_ratio             0.5

bspc config borderless_monocle      true
bspc config gapless_monocle         true
bspc config focus_follows_pointer   true
bspc config auto_alternate          true
bspc config auto_cancel             true

bspc config normal_frame_opacity    0.0
bspc config focused_frame_opacity   0.1

bspc monitor -d term web editor misc music

bspc rule -a Chromium desktop=^2
bspc rule -a nitrogen floating=on center=true

# Autostart apps

xsetroot -cursor_name left_ptr &
# Start Compton composting manager
compton --config ~/.config/compton.conf -b

nitrogen --restore
sxhkd -f 100 &
