nix-config: ENC[AES256_GCM,data:o+NVHp/bIqnXcWYco8KxQ45lDbBOSi90muZDxapLMZ5gBwZUfL32pWAT8Nuqmqqt6AMF9gG03H0aN+y2q2DZ0dsZLiQRVFO63oanqfAXGiBczo9roE/ldd9sNQ7sc4kbwBO8wa1E1fxLYWUhBhzrjMd9F1nMBSIj,iv:j8KxCcV4YG2hYg0W6/cV9+zcsN6gZLhgb3id/s1LX7s=,tag:Pkrs7UWVEyuyEuRlDI03dw==,type:str]
sops:
    age:
        - recipient: age1wja2r663c9t73ylvxetddvrzw4slvgtwjlscn4v8qsk52fkkccjqwpt5rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBSR0FISjhEVGxsMWRKTTJJ
            dytzMlVKZ2tuejV5L0loV2drVEh4UE8yekh3Cnk1UzdGeVVzL09XNFBpVWx6Y0Rm
            bnNyM0dESHNHWU9Ecy9zdk95MDBrVE0KLS0tIE5GWDhLcmhEZ2YxNmV2TTVJVXlm
            TmhFQzQvVVpaaG5vcm1qb05zT0pVSUkK5gKgQQhjJH4ZyGW1OtcwkYpEbsSCNjtS
            fsczr5a6YE0aNqZ0aD+rcyTmC5kyrfZv+GT7yqdCjUCfT2sOrZ/cZA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-18T23:28:14Z"
    mac: ENC[AES256_GCM,data:OPhBBuc8Ac14iGreN4saJFYPwnRsLDi0AKKH9BL9qgg7Kw86hLNzVKwiO9kvPoWFbnMqrssVkuF4PxYhM0QCPIZq5xdjYW05U9fR4L/c8fKHRM6z4mx3dnD4p2v4Gl6NRtOK7jaPsyAIzt+zu9jNnHzMfmvXkT1ZSn/1YyGjIdQ=,iv:9XlwJETQgJcrNg2PBFO4ekpxsGTzChErNuKSLmDkTN0=,tag:AvS4F/n812G8EaT6I6qRfA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
