github-token: ENC[AES256_GCM,data:P69TzmDXVeKTH7S7VirUWOsWOK0CwVz66fNVKFqGbFyi68OYgFRp7zmEtQJlCvjSWdtYDCMGfhoG8mWmFOJAm6t8sHueCKeA3uxRwiAtNWYybkoQqVchZ46ied8ofBTsAi/H6ct+NDyW/FF5a2ji2cXQQZ9kDlP4,iv:njyAj/xX7nY0gfOX0jlkocIpqU7jQf2gJeU3OllgQj4=,tag:HYcdj+QxlRSUghiA6BhG2A==,type:str]
sops:
    age:
        - recipient: age1wja2r663c9t73ylvxetddvrzw4slvgtwjlscn4v8qsk52fkkccjqwpt5rd
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaRUVaTmVPZE4vU2paV3gw
            ckd0Y1Y1dngyUUsrUGhuNXhvcWY0K1pOVTNFCk5VRTJLaWIwelZ2bjZXRHFNcWhq
            Wld0M3FKakZ3dGhmME9pYllzeU1nSGcKLS0tIHJCcnpWOTJMWk1PUlNMdkFaVlF1
            WVZPWFNVdWptdjBZRmlHZUprN2JsL00KTcA40nhVdjRQNB6jUQykEwgM45T9INgm
            gouv4K124PrwOJlSTrtPngibHK8Z4JxMAecDYCJTFv2bj/5znzum2Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-26T20:19:36Z"
    mac: ENC[AES256_GCM,data:KKPzR2HLHTs7ARH2+x905aAwgOtmfueF20UBWfNP4zrIoKB53U50DkbThBSTxe5HkpomIDq2cpQ0V+WWtcROneVy8Uv4aYNgI/fKnEXDQ0SXVLuhQ0fw1ho5TG5Ht+hH2DB0jlhJ89cM1yaAPpSrOXOyyP86KeBd1+NSnrES6vU=,iv:SgbFAQKYRfn4dfEZCJnOQqG9qRaGB75ID7f7Ocg6IBE=,tag:9mwPlt/vQrdOa616Lhc7BA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
