#! /bin/sh

bspc config border_width        2
bspc config window_gap         12

bspc config split_ratio         0.52
bspc config borderless_monocle  true
bspc config gapless_monocle     true
bspc config focus_by_distance   true

bspc monitor -d term web editor misc music

bspc rule -a Chromium desktop=^2
bspc rule -a nitrogen floating=on center=true

# Autostart apps

# Read .Xresources
xrdb -merge ~/.Xresources &
xsetroot -cursor_name left_ptr &
# Start Compton composting manager
compton --config ~/.config/compton.conf -b

nitrogen --restore
sxhkd &
gnome-terminal &
bspwm_panel.sh &
