---
name: Dead code analysis

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  deadnix:
    runs-on: ubuntu-latest
    timeout-minutes: 3
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: cachix/install-nix-action@v21
      - uses: cachix/cachix-action@v12
        with:
          name: deadnix
      - uses: astro/deadnix-action@main
